Improve performance for large models with DomainViewDict
openmc-dev/plotter pull request #138
Opened 2024-03-25 18:36 UTC by paulromano

If you run the plotter on a model with lots of cells (the ITER E-lite model, for example), it spends a lot of time copying data around unnecessarily. The crux of the issue is this line:
https://github.com/openmc-dev/plotter/blob/e772fb9ba55532ea984c4eb529c7fbf2982268f0/openmc_plotter/plotmodel.py#L321

which deepcopies the entire `PlotView` object. This object holds dictionaries called `cells` and `materials` that map cell and material IDs to `DomainView` objects (one for each cell and material that appears in the model). When I plot the ITER E-lite model, which has >300k cells, those deepcopies take about 12 seconds on my machine, which means that every time I update the plot view, there is a lag of 12 seconds even when the plot resolution is super low.

This PR makes a fairly easy fix to this problem, which is to store a global dictionary that holds the default `DomainView` view settings that are created at startup *separately* from the `PlotView` object itself. If you make a modification to the domain view (e.g., changing the color of a material), it does get stored as part the `PlotView` object and will get copied around, but the default domain views remain untouched and don't get copied.

2024-03-25 18:43 UTC, paulromano commented
Here's what it looks like working with E-lite on my laptop:
![plotter_domainviewdict](https://github.com/openmc-dev/plotter/assets/743095/0e7d7973-7c2c-42db-9ae9-8fb6568703e4)

2024-03-27 04:52 UTC, paulromano commented
Just added a commit which shaves off about ~7 sec of initialization time for the E-lite model

2024-03-27 14:29 UTC, paulromano commented
...and just made another commit that shaved _another_ 7 sec off initialization. Generating the default `DomainView` objects for each domain took about 20 sec before for the E-lite model and now it's down to 5 sec.

2024-03-27 15:14 UTC, pshriwise commented
Good idea to de-couple those from the `PlotView`'s -- no reason we need to bring them along in the copy. Any reason we shouldn't put those global dictionaries on the `PlotModel` object?

2024-03-28 04:40 UTC, paulromano commented
@pshriwise The global dictionaries are accessed from the `DomainViewDict` class, which is separate from the `PlotModel` class

2024-03-28 04:58 UTC, pshriwise commented
> @pshriwise The global dictionaries are accessed from the DomainViewDict class, which is separate from the PlotModel class. 

Understood, but any reason not to make the `DomainViewDict` class an attribute of the `PlotModel` class? I think this sticks more closely to the MVC approach this app is intended to take.

2024-03-30 10:34 UTC, paulromano commented
Ok, I was able to come up with a better (I think?) solution here. Instead of storing the defaults as a global dictionary, they are stored as an attribute on `DomainViewDict`. To avoid the original issue with all the defaults being deepcopied, I overrode the `__deepcopy__` method to make it only copy a reference of the defaults dictionary. Let me know what you think now @pshriwise

2024-03-31 18:00 UTC, pshriwise requested changes
Just one small question about a change to the default pixel size, but then I think this is ready! 🚀 

Thanks for this update! I tried out the E-lite model out (both before and after these changes) and it makes a big difference -- bring on the detail!

2024-03-31 18:00 UTC, pshriwise commented on openmc_plotter/plotmodel.py
> +        self.h_res = 100
Do we want to change the default pixel values permanently? I think for most models this default is manageable.

2024-03-31 18:01 UTC, pshriwise commented on openmc_plotter/plotmodel.py
> +        self.h_res = 100
Come to think of it, being able to set the initial number of pixels might be a nice option to have -- making an issue...

2024-04-02 14:21 UTC, paulromano commented on openmc_plotter/plotmodel.py
> +        self.h_res = 100
That was unintentional, got a little overzealous with git commit -a :blush: But yes! we absolutely should have an option to change the default resolution

2024-04-02 14:30 UTC, pshriwise commented on openmc_plotter/plotmodel.py
> +        self.h_res = 100
Ah, right one. Issue #139 created so we can tackle that later. Thanks!!

2024-04-02 14:30 UTC, pshriwise approved these changes
Thanks for the performance upgrade @paulromano!

2024-04-02 14:30 UTC, merged