Adding support for viewing distribcell tallies
openmc-dev/plotter pull request #87
Opened 2022-04-26 18:37 UTC by pshriwise

@paulromano must have had the same thought that I did in the NEA workshop today and created #86. Plotting these from the Python API is possible, but tricky. This adds that capability to the plotter.

2022-04-26 18:37 UTC, pshriwise commented
![image](https://user-images.githubusercontent.com/4563941/165369146-b800d946-9aff-44d8-98b7-94400cb62dd8.png)

2022-04-26 18:40 UTC, pshriwise commented
This is still a little rough, so I'm marking it as a draft for now. Just wanted to get it opened while the whole thing was in my head.

2022-04-27 04:06 UTC, paulromano commented on openmc_plotter/plotmodel.py
> +            image_data[np.logical_and(cell_id_mask, instance_mask)] = v
```suggestion
            image_data[cell_id_mask & instance_mask] = v
```

2022-04-27 20:14 UTC, paulromano requested changes

2022-04-27 20:14 UTC, paulromano commented on openmc_plotter/plotmodel.py
> +    def _create_distribcell_image(self, tally, tally_value, scores, nuclides):
Either this needs `view` as a last argument, or the calls to this method should not pass `view`

2022-04-27 20:14 UTC, paulromano commented on openmc_plotter/plotmodel.py
> +        sp = self.statepoint
```suggestion
```

2022-04-27 20:14 UTC, paulromano commented on openmc_plotter/plotmodel.py
> +        image_data = np.zeros_like(self.ids)
I tried out this branch and it wasn't working for me; eventually traced it down to this!
```suggestion
        image_data = np.zeros_like(self.ids, dtype=float)
```

Also, for a distribcell tally, should we not set the initial state to all `np.nan` instead of all zeros? It doesn't really make sense to me to assign zero values to locations in the image data where we don't have matching bins.

2022-04-27 22:01 UTC, paulromano approved these changes
Works great now -- thanks for this awesome feature!

2022-04-27 22:01 UTC, merged